name: Run API tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      
    - name: Run API tests
      run: dotnet test --logger "trx;LogFileName=test-results.trx"

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: csharp-api-xunit/TestResults/test-results.trx
